Change from px to rem in fonts
Platzi-Master-C8/gethired-base pull request #2
Opened 2021-11-23 02:43 UTC by IrvingJuarez

2021-11-23 15:38 UTC, j0s3v4rg4s submitted a review, later dismissed

2021-11-23 18:50 UTC, gndx approved these changes, later dismissed

2021-11-23 19:23 UTC, yadurani submitted a review, later dismissed

2021-11-23 20:04 UTC, yadurani submitted a review, later dismissed

2021-11-23 21:02 UTC, j0s3v4rg4s requested changes

2021-11-23 21:02 UTC, j0s3v4rg4s commented on package.json
> +  "version": "1.0.2",
```suggestion
  "version": "1.0.3",
```

2021-11-23 23:39 UTC, j0s3v4rg4s submitted a review, later dismissed

2021-11-24 00:52 UTC, yadurani approved these changes, later dismissed

2021-11-24 16:33 UTC, yadurani approved these changes

2021-11-24 16:37 UTC, j0s3v4rg4s approved these changes

2021-11-24 16:38 UTC, merged